import type {
    Transcript,
    TranscriptCourse,
    TranscriptModule,
    TranscriptLesson,
} from "@/types/transcript";

export const mockCourses: TranscriptCourse[] = [
    { id: 1, name: "Marketing Digital Completo" },
    { id: 2, name: "Copywriting Avançado" },
    { id: 3, name: "Tráfego Pago" },
];

export const mockModules: TranscriptModule[] = [
    { id: 1, name: "Introdução", courseId: 1 },
    { id: 2, name: "Estratégias de Conteúdo", courseId: 1 },
    { id: 3, name: "Fundamentos da Copy", courseId: 2 },
    { id: 4, name: "Headlines com IA", courseId: 2 },
    { id: 5, name: "Facebook Ads", courseId: 3 },
];

export const mockLessons: TranscriptLesson[] = [
    { id: 1, name: "Boas-vindas ao Curso", moduleId: 1 },
    { id: 2, name: "O que é Marketing Digital?", moduleId: 1 },
    { id: 3, name: "Criando Conteúdo Viral", moduleId: 2 },
    { id: 4, name: "O Poder das Palavras", moduleId: 3 },
    { id: 5, name: "Headlines que Convertem", moduleId: 4 },
    { id: 6, name: "Configurando sua Primeira Campanha", moduleId: 5 },
];

export const mockTranscripts: Transcript[] = [
    {
        id: 1,
        lessonId: 1,
        lessonName: "Boas-vindas ao Curso",
        moduleId: 1,
        moduleName: "Introdução",
        courseId: 1,
        courseName: "Marketing Digital Completo",
        text: "Olá, bem-vindo ao curso de Marketing Digital Completo! Nesta jornada, vamos explorar as principais estratégias para você dominar o marketing digital e alavancar seus resultados...",
        vector: "Apresentação do curso de marketing digital com visão geral das estratégias que serão ensinadas, incluindo conteúdo, tráfego e conversão.",
        keywords: ["marketing digital", "boas-vindas", "estratégias", "conteúdo"],
        wordCount: 1250,
        createdAt: "2026-02-15",
        updatedAt: "2026-02-18",
    },
    {
        id: 2,
        lessonId: 3,
        lessonName: "Criando Conteúdo Viral",
        moduleId: 2,
        moduleName: "Estratégias de Conteúdo",
        courseId: 1,
        courseName: "Marketing Digital Completo",
        text: "Conteúdo viral não é sorte, é estratégia. Nesta aula vamos entender os gatilhos psicológicos que fazem um conteúdo ser compartilhado...",
        vector: "Técnicas para criar conteúdo com alto potencial de viralização usando gatilhos psicológicos e storytelling.",
        keywords: ["conteúdo viral", "gatilhos", "storytelling", "engajamento", "redes sociais"],
        wordCount: 2100,
        createdAt: "2026-02-16",
        updatedAt: "2026-02-19",
    },
    {
        id: 3,
        lessonId: 4,
        lessonName: "O Poder das Palavras",
        moduleId: 3,
        moduleName: "Fundamentos da Copy",
        courseId: 2,
        courseName: "Copywriting Avançado",
        text: "Cada palavra que você escreve tem o poder de mover alguém emocionalmente. Copywriting é a arte de usar palavras para persuadir...",
        vector: "Fundamentos de copywriting focando na persuasão emocional e no uso estratégico de palavras para converter.",
        keywords: ["copywriting", "persuasão", "palavras", "conversão"],
        wordCount: 1800,
        createdAt: "2026-02-17",
        updatedAt: "2026-02-20",
    },
    {
        id: 4,
        lessonId: 5,
        lessonName: "Headlines que Convertem",
        moduleId: 4,
        moduleName: "Headlines com IA",
        courseId: 2,
        courseName: "Copywriting Avançado",
        text: "A headline é responsável por 80% do sucesso de qualquer peça de copy. Nesta aula, vamos aprender fórmulas testadas...",
        vector: "Fórmulas e técnicas para criar headlines de alta conversão utilizando inteligência artificial como ferramenta auxiliar.",
        keywords: ["headlines", "conversão", "IA", "fórmulas", "copy"],
        wordCount: 1650,
        createdAt: "2026-02-18",
        updatedAt: "2026-02-20",
    },
    {
        id: 5,
        lessonId: 6,
        lessonName: "Configurando sua Primeira Campanha",
        moduleId: 5,
        moduleName: "Facebook Ads",
        courseId: 3,
        courseName: "Tráfego Pago",
        text: "Vamos configurar juntos sua primeira campanha no Facebook Ads. Passo a passo, desde a escolha do objetivo...",
        vector: "Tutorial prático passo a passo de como configurar uma campanha de Facebook Ads do zero ao lançamento.",
        keywords: ["facebook ads", "tráfego pago", "campanha", "configuração"],
        wordCount: 2400,
        createdAt: "2026-02-19",
        updatedAt: "2026-02-20",
    },
];
