import type { PromoteItem } from "@/types/promote";

export const mockPromotions: PromoteItem[] = [
    {
        id: 1,
        title: "Mega Promoção de Verão",
        description: "Aproveite 50% de desconto em todos os cursos selecionados. Válido por tempo limitado!",
        mediaType: "image",
        mediaUrl: "",
        startDate: "2026-02-15",
        endDate: "2026-03-15",
        hasCta: true,
        ctaText: "Aproveitar Agora",
        ctaUrl: "https://exemplo.com/promo-verao",
        ctaDelay: 5,
        status: "active",
        isActive: true,
        views: 1240,
        clicks: 186,
        createdAt: "2026-02-10T10:00:00Z",
    },
    {
        id: 2,
        title: "Black Friday Especial",
        description: "Os maiores descontos do ano em cursos premium. Até 70% off!",
        mediaType: "video",
        mediaUrl: "https://youtube.com/watch?v=example",
        startDate: "2026-11-25",
        endDate: "2026-11-30",
        hasCta: true,
        ctaText: "Comprar Agora",
        ctaUrl: "https://exemplo.com/blackfriday",
        ctaDelay: 3,
        status: "upcoming",
        isActive: true,
        views: 0,
        clicks: 0,
        createdAt: "2026-02-08T14:30:00Z",
    },
    {
        id: 3,
        title: "Boas-vindas ao Aluno",
        description: "Ganhe um módulo extra gratuito ao se inscrever em qualquer curso!",
        mediaType: "image",
        mediaUrl: "",
        startDate: "2026-01-01",
        endDate: "2026-01-31",
        hasCta: false,
        ctaText: "",
        ctaUrl: "",
        ctaDelay: 0,
        status: "expired",
        isActive: false,
        views: 3580,
        clicks: 412,
        createdAt: "2025-12-20T09:00:00Z",
    },
    {
        id: 4,
        title: "Curso Novo — Lançamento",
        description: "Confira o novo curso de Marketing Digital com condições exclusivas de pré-venda.",
        mediaType: "video",
        mediaUrl: "https://youtube.com/watch?v=launch",
        startDate: "2026-03-01",
        endDate: "2026-03-20",
        hasCta: true,
        ctaText: "Garantir Vaga",
        ctaUrl: "https://exemplo.com/lancamento",
        ctaDelay: 10,
        status: "upcoming",
        isActive: true,
        views: 0,
        clicks: 0,
        createdAt: "2026-02-18T16:00:00Z",
    },
    {
        id: 5,
        title: "Flash Sale — 24h",
        description: "Promoção relâmpago com 30% de desconto. Só hoje!",
        mediaType: "image",
        mediaUrl: "",
        startDate: "2026-02-20",
        endDate: "2026-02-21",
        hasCta: true,
        ctaText: "Aproveitar",
        ctaUrl: "https://exemplo.com/flash",
        ctaDelay: 0,
        status: "active",
        isActive: true,
        views: 890,
        clicks: 134,
        createdAt: "2026-02-19T08:00:00Z",
    },
];
