import type { Course } from "@/types/course";

/** Mock courses — will be replaced with API data */
export const mockCourses: Course[] = [
    {
        id: 1,
        name: "Marketing Digital Avançado",
        description: "Aprenda as estratégias mais avançadas de marketing digital para escalar seu negócio.",
        image: "",
        category: "principal",
        studentsCount: 234,
        lessonsCount: 45,
        createdAt: "2026-02-01",
        isPublished: true,
    },
    {
        id: 2,
        name: "Copywriting que Vende",
        description: "Domine a arte de escrever textos persuasivos que convertem visitantes em clientes.",
        image: "",
        category: "principal",
        studentsCount: 189,
        lessonsCount: 32,
        createdAt: "2026-01-15",
        isPublished: true,
    },
    {
        id: 3,
        name: "Pack de Templates",
        description: "Templates prontos para usar em seus anúncios e landing pages.",
        image: "",
        category: "order_bump",
        studentsCount: 156,
        lessonsCount: 8,
        createdAt: "2026-02-10",
        isPublished: true,
    },
    {
        id: 4,
        name: "Mentoria VIP",
        description: "Acesso exclusivo a mentorias em grupo com acompanhamento individualizado.",
        image: "",
        category: "upsell",
        studentsCount: 42,
        lessonsCount: 12,
        createdAt: "2026-02-05",
        isPublished: true,
    },
    {
        id: 5,
        name: "Planilha de Métricas",
        description: "Planilha completa para acompanhar todas as métricas do seu negócio digital.",
        image: "",
        category: "bonus",
        studentsCount: 198,
        lessonsCount: 3,
        createdAt: "2026-01-20",
        isPublished: true,
    },
    {
        id: 6,
        name: "Tráfego Pago Masterclass",
        description: "Curso completo sobre Facebook Ads, Google Ads e estratégias de escala.",
        image: "",
        category: "principal",
        studentsCount: 312,
        lessonsCount: 58,
        createdAt: "2025-12-10",
        isPublished: false,
    },
];
